name: Heartbeat API Check Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request and log response
        run: |
          RESPONSE=$(curl -s -X POST "https://hifz-tracker-v3-server.onrender.com/login" \
            -H "Content-Type: application/json" \
            -d '{
              "email": "heartbeat@hifz.com",
              "password": "user123"
            }')
          echo "API Response:"
          echo "$RESPONSE"

